# name must match what's in Supabase 'universities.name' (the Scorecard official name)
# Format: (search_key_for_db, ed1, ed2, ea, rd, notes)
DEADLINES = [
    ("Harvard", None, None, "1-Nov (REA)", "1-Jan", "~typical, verify"),
    ("Yale", None, None, "1-Nov (SCEA)", "2-Jan", "~typical, verify"),
    ("Princeton", None, None, "1-Nov (SCEA)", "1-Jan", "~typical, verify"),
    ("Massachusetts Institute of Technology", None, None, "1-Nov", "1-Jan", "~typical, verify"),
    ("California Institute of Technology", None, None, "1-Nov", "3-Jan", "~typical, verify"),
    ("Dartmouth", "1-Nov", None, None, "2-Jan", "~typical, verify"),
    ("Brown", "1-Nov", None, None, "1-Jan", "NB since 2025 (Class of 2029)"),
    ("Columbia", "1-Nov", None, None, "1-Jan", "~typical, verify"),
    ("University of Pennsylvania", "1-Nov", None, None, "5-Jan", "~typical, verify"),
    ("Cornell University", "1-Nov", None, None, "2-Jan", "~typical, verify"),
    ("Stanford University", None, None, "1-Nov (REA)", "5-Jan", "~typical, verify"),
    ("University of Chicago", "1-Nov", "3-Jan", "1-Nov", "3-Jan", "EA + ED both offered"),
    ("Duke University", "2-Nov", None, None, "4-Jan", None),
    ("Vanderbilt University", "1-Nov", "1-Jan", None, "1-Jan", None),
    ("Rice University", "1-Nov", "4-Jan", None, "4-Jan", None),
    ("Northwestern University", "1-Nov", None, None, "2-Jan", None),
    ("Johns Hopkins University", "1-Nov", "2-Jan", None, "2-Jan", None),
    ("Washington University in St Louis", "2-Nov", "4-Jan", "2-Nov", "4-Jan", None),
    ("Georgetown University", None, None, "1-Nov", "10-Jan", None),
    ("Emory University", "1-Nov", "1-Jan", None, "1-Jan", None),
    ("Tufts University", "2-Nov", "4-Jan", None, "4-Jan", None),
    ("Carnegie Mellon University", "3-Nov", None, None, "5-Jan", None),
    ("University of Notre Dame", None, None, "1-Nov", "2-Jan", None),
    ("Boston College", "1-Nov", "2-Jan", None, "2-Jan", None),
    ("Tulane University of Louisiana", "1-Nov", "5-Jan", "10-Nov", "15-Jan", None),
    ("New York University", "1-Nov", "1-Jan", None, "5-Jan", None),
    ("Wake Forest University", "15-Nov", "1-Jan", "15-Nov", "1-Jan", "Merit-only for intl"),
    ("Northeastern University", "1-Nov", "1-Jan", "1-Nov", "1-Jan", None),
    ("University of Southern California", "1-Nov", None, "1-Nov", "10-Jan", None),
    ("Pomona College", "15-Nov", "15-Jan", None, "15-Jan", "QuestBridge Nov 1"),
    ("Grinnell College", "15-Nov", "5-Jan", None, "15-Jan", None),
    ("Davidson College", "15-Nov", "5-Jan", None, "12-Jan", None),
    ("Claremont McKenna College", "1-Nov", "10-Jan", None, "10-Jan", "Merit priority Dec 1"),
    ("Middlebury College", "1-Nov", "3-Jan", None, "3-Jan", None),
    ("Colby College", "15-Nov", "5-Jan", None, "5-Jan", None),
    ("Bates College", "15-Nov", "10-Jan", None, "10-Jan", None),
    ("Colgate University", "1-Nov", "15-Jan", None, "15-Jan", None),
    ("Hamilton College", "15-Nov", "5-Jan", None, "5-Jan", None),
    ("Oberlin College", "1-Nov", "2-Jan", None, "15-Jan", None),
    ("Kenyon College", "15-Nov", "15-Jan", None, "15-Jan", None),
    ("Skidmore College", "1-Nov", "8-Jan", None, "8-Jan", None),
    ("Lafayette College", "1-Nov", "5-Jan", None, "5-Jan", None),
    ("Lehigh University", "1-Nov", "1-Jan", None, "1-Jan", None),
    ("University of Richmond", "1-Nov", None, "1-Nov", "1-Jan", "EA Nov 1"),
    ("Macalester College", "1-Nov", "1-Jan", "1-Nov", "15-Jan", "EA Nov 1"),
    ("Babson College", "1-Nov", "2-Jan", "1-Nov", "2-Jan", "EA Nov 1"),
    ("Case Western Reserve University", "1-Nov", "15-Jan", "1-Nov", "15-Jan", "EA Nov 1"),
    ("Denison University", "15-Nov", "15-Jan", None, "15-Jan", None),
    ("Dickinson College", "1-Nov", "15-Jan", None, "15-Jan", None),
    ("Franklin and Marshall College", "15-Nov", "15-Jan", None, "15-Jan", None),
    ("Trinity College", "15-Nov", "15-Jan", None, "15-Jan", None),
    ("Connecticut College", "1-Nov", "15-Jan", "1-Nov", "15-Jan", "EA Nov 1"),
    ("Gettysburg College", "15-Nov", "15-Jan", "1-Dec", "15-Jan", "EA Dec 1"),
    ("University of Oregon", None, None, "1-Nov", "15-Jan", "ICSP $7.5k-30k, 66-80hrs service"),
    ("Elon University", "1-Nov", None, "1-Nov", "10-Jan", None),
    ("High Point University", "Rolling", None, None, "Rolling", None),
    ("Rollins College", "1-Nov", "5-Jan", "15-Nov", "1-Feb", None),
    ("Stetson University", "Rolling", None, None, "Rolling", None),
    ("Roanoke College", "Rolling", None, None, "Rolling", None),
    ("Eckerd College", "Rolling", None, None, "Rolling", None),
    ("Florida Southern College", "Rolling", None, None, "Rolling", None),
    ("Mercer University", None, None, "1-Nov", "1-Feb", None),
    ("Belmont University", "Rolling", None, None, "Rolling", None),
    ("University of Tampa", "Rolling", None, None, "Rolling", None),
    ("Susquehanna University", "Rolling", None, None, "Rolling", None),
    ("McDaniel College", "Rolling", None, None, "Rolling", None),
    ("University of Lynchburg", "Rolling", None, None, "Rolling", None),
    ("Arcadia University", "Rolling", None, None, "Rolling", None),
    ("Hartwick College", "Rolling", None, None, "Rolling", None),
    ("Catawba College", "Rolling", None, None, "Rolling", None),
    ("Wofford College", "1-Nov", None, "15-Nov", "15-Jan", None),
    ("Millsaps College", "Rolling", None, None, "Rolling", None),
    ("Maryville College", "Rolling", None, None, "Rolling", None),
    ("Lenoir-Rhyne University", "Rolling", None, None, "Rolling", None),
    ("Lyon College", "Rolling", None, None, "Rolling", None),
    ("Marymount University", "Rolling", None, None, "Rolling", None),
    ("Centenary College of Louisiana", "Rolling", None, None, "Rolling", None),
    ("Coastal Carolina University", "15-Oct", None, "15-Nov", "1-Feb", None),
    ("Hampden-Sydney College", "1-Dec", "1-Dec", "15-Oct", "1-Feb", "Merit + limited need"),
    ("University of Alabama", None, None, None, "Rolling", None),
    ("University of Mississippi", None, None, None, "Rolling", None),
    ("Western New England University", None, None, None, "Rolling", None),
    ("Eastern New Mexico University-Main Campus", None, None, None, "Rolling", "Open admission"),
    ("Minot State University", None, None, None, "Rolling", "Open admission"),
    ("Valley City State University", None, None, None, "Rolling", "Open admission"),
    ("University of Maine at Fort Kent", None, None, None, "Rolling", "Open admission"),
    ("Dickinson State University", None, None, None, "Rolling", "Open admission"),
    ("Mayville State University", None, None, None, "Rolling", "Open admission"),
    ("University of Maine at Presque Isle", None, None, None, "Rolling", "Open admission"),
    ("Bemidji State University", None, None, None, "Rolling", "Open admission"),
    ("University of Montana Western", None, None, None, "Rolling", "Open admission"),
    ("Dakota State University", None, None, None, "Rolling", "Open admission"),
    ("Peru State College", None, None, None, "Rolling", "Open admission"),
    ("University of Science and Arts of Oklahoma", None, None, None, "Rolling", "Open admission"),
    ("Bluefield State University", None, None, None, "Rolling", "Open admission"),
    ("Concord University", None, None, None, "Rolling", "Open admission"),
    ("Glenville State University", None, None, None, "Rolling", "Open admission"),
    ("West Virginia State University", None, None, None, "Rolling", "Open admission"),
    ("Berry College", None, None, "1-Nov", "Rolling", "Merit aid for intl; verify dates"),
    ("Shepherd University", None, None, None, "Rolling", "Near-open admission; verify"),
]
