UNIVERSITIES_100 = [
    # ELITE - tier 1
    {"name": "Harvard University", "tier": 1, "aid_status": "NB", "scorecard_id": 166027},
    {"name": "Yale University", "tier": 1, "aid_status": "NB", "scorecard_id": 130794},
    {"name": "Princeton University", "tier": 1, "aid_status": "NB", "scorecard_id": 186131},
    {"name": "Massachusetts Institute of Technology", "tier": 1, "aid_status": "NB", "scorecard_id": 166683},
    {"name": "California Institute of Technology", "tier": 1, "aid_status": "NB", "scorecard_id": 110404},
    {"name": "Dartmouth College", "tier": 1, "aid_status": "NB", "scorecard_id": 182670},
    {"name": "Brown University", "tier": 1, "aid_status": "NB", "scorecard_id": 217156},
    {"name": "Columbia University in the City of New York", "tier": 1, "aid_status": "NA", "scorecard_id": 190150},
    {"name": "University of Pennsylvania", "tier": 1, "aid_status": "NA", "scorecard_id": 215062},
    {"name": "Cornell University", "tier": 1, "aid_status": "NA", "scorecard_id": 190415},
    {"name": "Stanford University", "tier": 1, "aid_status": "NA", "scorecard_id": 243744},
    {"name": "University of Chicago", "tier": 1, "aid_status": "NA", "scorecard_id": 144050},
    # TOP - tier 2
    {"name": "Duke University", "tier": 2, "aid_status": "NA", "scorecard_id": 198419},
    {"name": "Vanderbilt University", "tier": 2, "aid_status": "NA", "scorecard_id": 221999},
    {"name": "Rice University", "tier": 2, "aid_status": "NA", "scorecard_id": 227757},
    {"name": "Northwestern University", "tier": 2, "aid_status": "NA", "scorecard_id": 147767},
    {"name": "Johns Hopkins University", "tier": 2, "aid_status": "NA", "scorecard_id": 162928},
    {"name": "Washington University in St Louis", "tier": 2, "aid_status": "NA", "scorecard_id": 179867},
    {"name": "Georgetown University", "tier": 2, "aid_status": "NA", "scorecard_id": 131496},
    {"name": "Emory University", "tier": 2, "aid_status": "NA", "scorecard_id": 139658},
    {"name": "Tufts University", "tier": 2, "aid_status": "NA", "scorecard_id": 168148},
    {"name": "Carnegie Mellon University", "tier": 2, "aid_status": "NA", "scorecard_id": 211440},
    {"name": "University of Notre Dame", "tier": 2, "aid_status": "NA", "scorecard_id": 152080},
    {"name": "Boston College", "tier": 2, "aid_status": "NA", "scorecard_id": 164924},
    {"name": "Tulane University of Louisiana", "tier": 2, "aid_status": "ME", "scorecard_id": 160755},
    {"name": "New York University", "tier": 2, "aid_status": "NA", "scorecard_id": 193900},
    {"name": "Wake Forest University", "tier": 2, "aid_status": "ME", "scorecard_id": 199847},
    {"name": "Northeastern University", "tier": 2, "aid_status": "NA", "scorecard_id": 167358},
    {"name": "University of Southern California", "tier": 2, "aid_status": "NA", "scorecard_id": 123961},
    # REGULAR - tier 3
    {"name": "Pomona College", "tier": 3, "aid_status": "NA", "scorecard_id": 121345},
    {"name": "Grinnell College", "tier": 3, "aid_status": "NA", "scorecard_id": 153384},
    {"name": "Davidson College", "tier": 3, "aid_status": "NA", "scorecard_id": 198385},
    {"name": "Claremont McKenna College", "tier": 3, "aid_status": "NA", "scorecard_id": 112260},
    {"name": "Middlebury College", "tier": 3, "aid_status": "NA", "scorecard_id": 230959},
    {"name": "Colby College", "tier": 3, "aid_status": "NA", "scorecard_id": 161086},
    {"name": "Bates College", "tier": 3, "aid_status": "NA", "scorecard_id": 160977},
    {"name": "Colgate University", "tier": 3, "aid_status": "NA", "scorecard_id": 190099},
    {"name": "Hamilton College", "tier": 3, "aid_status": "NA", "scorecard_id": 191515},
    {"name": "Oberlin College", "tier": 3, "aid_status": "NA", "scorecard_id": 204501},
    {"name": "Kenyon College", "tier": 3, "aid_status": "NA", "scorecard_id": 203535},
    {"name": "Skidmore College", "tier": 3, "aid_status": "NA", "scorecard_id": 195526},
    {"name": "Lafayette College", "tier": 3, "aid_status": "NA", "scorecard_id": 213385},
    {"name": "Lehigh University", "tier": 3, "aid_status": "NA", "scorecard_id": 213543},
    {"name": "University of Richmond", "tier": 3, "aid_status": "NA", "scorecard_id": 232566},
    {"name": "Macalester College", "tier": 3, "aid_status": "NA", "scorecard_id": 173902},
    {"name": "Babson College", "tier": 3, "aid_status": "NA", "scorecard_id": 164580},
    {"name": "Case Western Reserve University", "tier": 3, "aid_status": "NA", "scorecard_id": 201645},
    {"name": "Denison University", "tier": 3, "aid_status": "NA", "scorecard_id": 202523},
    {"name": "Dickinson College", "tier": 3, "aid_status": "NA", "scorecard_id": 212009},
    {"name": "Franklin and Marshall College", "tier": 3, "aid_status": "NA", "scorecard_id": 212984},
    {"name": "Trinity College", "tier": 3, "aid_status": "NA", "scorecard_id": 130590},
    {"name": "Connecticut College", "tier": 3, "aid_status": "NA", "scorecard_id": 128902},
    {"name": "Gettysburg College", "tier": 3, "aid_status": "NA", "scorecard_id": 212674},
    {"name": "University of Oregon", "tier": 3, "aid_status": "NB", "scorecard_id": 209551},
    # EASY - tier 4
    {"name": "Elon University", "tier": 4, "aid_status": "NA", "scorecard_id": 198516},
    {"name": "High Point University", "tier": 4, "aid_status": "NA", "scorecard_id": 198695},
    {"name": "Rollins College", "tier": 4, "aid_status": "NA", "scorecard_id": 136950},
    {"name": "Stetson University", "tier": 4, "aid_status": "NA", "scorecard_id": 137546},
    {"name": "Roanoke College", "tier": 4, "aid_status": "NA", "scorecard_id": 233426},
    {"name": "Eckerd College", "tier": 4, "aid_status": "ME", "scorecard_id": 133492},
    {"name": "Florida Southern College", "tier": 4, "aid_status": "ME", "scorecard_id": 134079},
    {"name": "Mercer University", "tier": 4, "aid_status": "ME", "scorecard_id": 140447},
    {"name": "Belmont University", "tier": 4, "aid_status": "ME", "scorecard_id": 219709},
    {"name": "University of Tampa", "tier": 4, "aid_status": "ME", "scorecard_id": 137847},
    {"name": "Susquehanna University", "tier": 4, "aid_status": "ME", "scorecard_id": 216278},
    {"name": "McDaniel College", "tier": 4, "aid_status": "ME", "scorecard_id": 164270},
    {"name": "University of Lynchburg", "tier": 4, "aid_status": "ME", "scorecard_id": 232609},
    {"name": "Arcadia University", "tier": 4, "aid_status": "ME", "scorecard_id": 211088},
    {"name": "Hartwick College", "tier": 4, "aid_status": "ME", "scorecard_id": 191533},
    {"name": "Catawba College", "tier": 4, "aid_status": "ME", "scorecard_id": 198215},
    {"name": "Wofford College", "tier": 4, "aid_status": "ME", "scorecard_id": 218973},
    {"name": "Millsaps College", "tier": 4, "aid_status": "ME", "scorecard_id": 175980},
    {"name": "Maryville College", "tier": 4, "aid_status": "ME", "scorecard_id": 220710},
    {"name": "Lenoir-Rhyne University", "tier": 4, "aid_status": "ME", "scorecard_id": 198835},
    {"name": "Lyon College", "tier": 4, "aid_status": "ME", "scorecard_id": 106342},
    {"name": "Marymount University", "tier": 4, "aid_status": "ME", "scorecard_id": 231651},
    {"name": "Centenary College of Louisiana", "tier": 4, "aid_status": "ME", "scorecard_id": 158477},
    {"name": "Coastal Carolina University", "tier": 4, "aid_status": "ME", "scorecard_id": 218724},
    {"name": "Hampden-Sydney College", "tier": 4, "aid_status": "ML", "scorecard_id": 232256},
    {"name": "Berry College", "tier": 4, "aid_status": "ME", "scorecard_id": 139144},
    # GUARANTEED - tier 5
    {"name": "University of Alabama", "tier": 5, "aid_status": "ME", "scorecard_id": 100751},
    {"name": "University of Mississippi", "tier": 5, "aid_status": "ME", "scorecard_id": 176017},
    {"name": "Western New England University", "tier": 5, "aid_status": "ME", "scorecard_id": 168254},
    {"name": "Eastern New Mexico University-Main Campus", "tier": 5, "aid_status": "ME", "scorecard_id": 187648},
    {"name": "Minot State University", "tier": 5, "aid_status": "ME", "scorecard_id": 200253},
    {"name": "Valley City State University", "tier": 5, "aid_status": "ME", "scorecard_id": 200572},
    {"name": "University of Maine at Fort Kent", "tier": 5, "aid_status": "ME", "scorecard_id": 161235},
    {"name": "Dickinson State University", "tier": 5, "aid_status": "ME", "scorecard_id": 200059},
    {"name": "Mayville State University", "tier": 5, "aid_status": "ME", "scorecard_id": 200226},
    {"name": "University of Maine at Presque Isle", "tier": 5, "aid_status": "ME", "scorecard_id": 161341},
    {"name": "Bemidji State University", "tier": 5, "aid_status": "ME", "scorecard_id": 173124},
    {"name": "University of Montana Western", "tier": 5, "aid_status": "ME", "scorecard_id": 180692},
    {"name": "Dakota State University", "tier": 5, "aid_status": "ME", "scorecard_id": 219082},
    {"name": "Peru State College", "tier": 5, "aid_status": "ME", "scorecard_id": 181534},
    {"name": "University of Science and Arts of Oklahoma", "tier": 5, "aid_status": "ME", "scorecard_id": 207722},
    {"name": "Bluefield State University", "tier": 5, "aid_status": "ME", "scorecard_id": 237215},
    {"name": "Concord University", "tier": 5, "aid_status": "ME", "scorecard_id": 237057},
    {"name": "Glenville State University", "tier": 5, "aid_status": "ME", "scorecard_id": 237385},
    {"name": "West Virginia State University", "tier": 5, "aid_status": "ME", "scorecard_id": 237899},
    {"name": "Shepherd University", "tier": 5, "aid_status": "ME", "scorecard_id": 237792},
]
