UNIVERSITIES_100 = [
    # ELITE - tier 1
    {"name": "Harvard University", "tier": 1, "aid_status": "NB", "scorecard_id": 166027},
    {"name": "Yale University", "tier": 1, "aid_status": "NB", "scorecard_id": 130794},
    {"name": "Princeton University", "tier": 1, "aid_status": "NB", "scorecard_id": 186131},
    {"name": "Massachusetts Institute of Technology", "tier": 1, "aid_status": "NB", "scorecard_id": 166683},
    {"name": "California Institute of Technology", "tier": 1, "aid_status": "NB", "scorecard_id": 110404},
    {"name": "Dartmouth College", "tier": 1, "aid_status": "NB", "scorecard_id": 182670},
    {"name": "Brown University", "tier": 1, "aid_status": "NB", "scorecard_id": 217156},
    {"name": "Columbia University in the City of New York", "tier": 1, "aid_status": "NA", "scorecard_id": 190150},
    {"name": "University of Pennsylvania", "tier": 1, "aid_status": "NA", "scorecard_id": 215062},
    {"name": "Cornell University", "tier": 1, "aid_status": "NA", "scorecard_id": 190415},
    {"name": "Stanford University", "tier": 1, "aid_status": "NA", "scorecard_id": 243744},
    {"name": "University of Chicago", "tier": 1, "aid_status": "NA", "scorecard_id": 144050},
    # TOP - tier 2
    {"name": "Duke University", "tier": 2, "aid_status": "NA", "scorecard_id": 153658},
    {"name": "Vanderbilt University", "tier": 2, "aid_status": "NA", "scorecard_id": 221999},
    {"name": "Rice University", "tier": 2, "aid_status": "NA", "scorecard_id": 227757},
    {"name": "Northwestern University", "tier": 2, "aid_status": "NA", "scorecard_id": 147767},
    {"name": "Johns Hopkins University", "tier": 2, "aid_status": "NA", "scorecard_id": 162928},
    {"name": "Washington University in St Louis", "tier": 2, "aid_status": "NA", "scorecard_id": 179867},
    {"name": "Georgetown University", "tier": 2, "aid_status": "NA", "scorecard_id": 131496},
    {"name": "Emory University", "tier": 2, "aid_status": "NA", "scorecard_id": 139755},
    {"name": "Tufts University", "tier": 2, "aid_status": "NA", "scorecard_id": 168148},
    {"name": "Carnegie Mellon University", "tier": 2, "aid_status": "NA", "scorecard_id": 211440},
    {"name": "University of Notre Dame", "tier": 2, "aid_status": "NA", "scorecard_id": 152080},
    {"name": "Boston College", "tier": 2, "aid_status": "NA", "scorecard_id": 164924},
    {"name": "Tulane University of Louisiana", "tier": 2, "aid_status": "ME", "scorecard_id": 160755},
    {"name": "New York University", "tier": 2, "aid_status": "NA", "scorecard_id": 193900},
    {"name": "Wake Forest University", "tier": 2, "aid_status": "ME", "scorecard_id": 200280},
    {"name": "Northeastern University", "tier": 2, "aid_status": "NA", "scorecard_id": 167358},,
    {"name": "University of Southern California", "tier": 2, "aid_status": "NA", "scorecard_id": 123961},
    # REGULAR - tier 3
    {"name": "Pomona College", "tier": 3, "aid_status": "NA", "scorecard_id": 121345},
    {"name": "Grinnell College", "tier": 3, "aid_status": "NA", "scorecard_id": 153384},
    {"name": "Davidson College", "tier": 3, "aid_status": "NA", "scorecard_id": 198419},
    {"name": "Claremont McKenna College", "tier": 3, "aid_status": "NA", "scorecard_id": 110486},
    {"name": "Middlebury College", "tier": 3, "aid_status": "NA", "scorecard_id": 230959},
    {"name": "Colby College", "tier": 3, "aid_status": "NA", "scorecard_id": 161004},
    {"name": "Bates College", "tier": 3, "aid_status": "NA", "scorecard_id": 160977},
    {"name": "Colgate University", "tier": 3, "aid_status": "NA", "scorecard_id": 190099},
    {"name": "Hamilton College", "tier": 3, "aid_status": "NA", "scorecard_id": 191515},
    {"name": "Oberlin College", "tier": 3, "aid_status": "NA", "scorecard_id": 204024},
    {"name": "Kenyon College", "tier": 3, "aid_status": "NA", "scorecard_id": 203535},
    {"name": "Skidmore College", "tier": 3, "aid_status": "NA", "scorecard_id": 195720},
    {"name": "Lafayette College", "tier": 3, "aid_status": "NA", "scorecard_id": 212911},
    {"name": "Lehigh University", "tier": 3, "aid_status": "NA", "scorecard_id": 213543},
    {"name": "University of Richmond", "tier": 3, "aid_status": "NA", "scorecard_id": 232566},
    {"name": "Macalester College", "tier": 3, "aid_status": "NA", "scorecard_id": 174792},
    {"name": "Babson College", "tier": 3, "aid_status": "NA", "scorecard_id": 164580},
    {"name": "Case Western Reserve University", "tier": 3, "aid_status": "NA", "scorecard_id": 201885},
    {"name": "Denison University", "tier": 3, "aid_status": "NA", "scorecard_id": 202134},
    {"name": "Dickinson College", "tier": 3, "aid_status": "NA", "scorecard_id": 212577},
    {"name": "Franklin and Marshall College", "tier": 3, "aid_status": "NA", "scorecard_id": 212984},
    {"name": "Trinity College", "tier": 3, "aid_status": "NA", "scorecard_id": 129020},
    {"name": "Connecticut College", "tier": 3, "aid_status": "NA", "scorecard_id": 128771},
    {"name": "Gettysburg College", "tier": 3, "aid_status": "NA", "scorecard_id": 213011},
    {"name": "University of Oregon", "tier": 3, "aid_status": "NB", "scorecard_id": 209551},
    # EASY - tier 4
    {"name": "Elon University", "tier": 4, "aid_status": "NA"},
    {"name": "High Point University", "tier": 4, "aid_status": "NA", "scorecard_id": 199120},
    {"name": "Rollins College", "tier": 4, "aid_status": "NA"},
    {"name": "Stetson University", "tier": 4, "aid_status": "NA"},
    {"name": "Roanoke College", "tier": 4, "aid_status": "NA", "scorecard_id": 233374},
    {"name": "Eckerd College", "tier": 4, "aid_status": "ME"},
    {"name": "Florida Southern College", "tier": 4, "aid_status": "ME"},
    {"name": "Mercer University", "tier": 4, "aid_status": "ME"},
    {"name": "Belmont University", "tier": 4, "aid_status": "ME"},
    {"name": "University of Tampa", "tier": 4, "aid_status": "ME", "scorecard_id": 137351},
    {"name": "Susquehanna University", "tier": 4, "aid_status": "ME"},
    {"name": "McDaniel College", "tier": 4, "aid_status": "ME"},
    {"name": "University of Lynchburg", "tier": 4, "aid_status": "ME"},
    {"name": "Arcadia University", "tier": 4, "aid_status": "ME"},
    {"name": "Hartwick College", "tier": 4, "aid_status": "ME"},
    {"name": "Catawba College", "tier": 4, "aid_status": "ME"},
    {"name": "Wofford College", "tier": 4, "aid_status": "ME"},
    {"name": "Millsaps College", "tier": 4, "aid_status": "ME"},
    {"name": "Maryville College", "tier": 4, "aid_status": "ME"},
    {"name": "Lenoir-Rhyne University", "tier": 4, "aid_status": "ME"},
    {"name": "Lyon College", "tier": 4, "aid_status": "ME"},
    {"name": "Marymount University", "tier": 4, "aid_status": "ME", "scorecard_id": 231651},
    {"name": "Centenary College of Louisiana", "tier": 4, "aid_status": "ME"},
    {"name": "Coastal Carolina University", "tier": 4, "aid_status": "ME"},
    {"name": "Hampden-Sydney College", "tier": 4, "aid_status": "ML"},
    {"name": "Berry College", "tier": 4, "aid_status": "ME"},
    # GUARANTEED - tier 5
    {"name": "University of Alabama", "tier": 5, "aid_status": "ME", "scorecard_id": 100751},
    {"name": "University of Mississippi", "tier": 5, "aid_status": "ME", "scorecard_id": 176080},
    {"name": "Western New England University", "tier": 5, "aid_status": "ME"},
    {"name": "Eastern New Mexico University-Main Campus", "tier": 5, "aid_status": "ME"},
    {"name": "Minot State University", "tier": 5, "aid_status": "ME"},
    {"name": "Valley City State University", "tier": 5, "aid_status": "ME"},
    {"name": "University of Maine at Fort Kent", "tier": 5, "aid_status": "ME"},
    {"name": "Dickinson State University", "tier": 5, "aid_status": "ME"},
    {"name": "Mayville State University", "tier": 5, "aid_status": "ME"},
    {"name": "University of Maine at Presque Isle", "tier": 5, "aid_status": "ME"},
    {"name": "Bemidji State University", "tier": 5, "aid_status": "ME"},
    {"name": "University of Montana Western", "tier": 5, "aid_status": "ME"},
    {"name": "Dakota State University", "tier": 5, "aid_status": "ME", "scorecard_id": 219471},
    {"name": "Peru State College", "tier": 5, "aid_status": "ME"},
    {"name": "University of Science and Arts of Oklahoma", "tier": 5, "aid_status": "ME", "scorecard_id": 207388},
    {"name": "Bluefield State University", "tier": 5, "aid_status": "ME"},
    {"name": "Concord University", "tier": 5, "aid_status": "ME", "scorecard_id": 237057},
    {"name": "Glenville State University", "tier": 5, "aid_status": "ME"},
    {"name": "West Virginia State University", "tier": 5, "aid_status": "ME"},
    {"name": "Shepherd University", "tier": 5, "aid_status": "ME"},
]
